import './globals.css';
import dynamic from 'next/dynamic';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { SidebarProvider } from '@/components/ui/sidebar';
import AppSidebarWrapper from './app-sidebar-wrapper';
import AppTopBar from '@/components/layout/app-topbar';

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex w-full">
            <AppSidebarWrapper />
            <div className="flex-1 w-full">
              <AppTopBar />
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
