import './globals.css';
import dynamic from 'next/dynamic';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { SidebarProvider } from '@/components/ui/sidebar';
import AppSidebarWrapper from './app-sidebar-wrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex w-full">
            <AppSidebarWrapper />
            <div className="flex-1 w-full">{children}</div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
